version: '3'
services:
  microapp-frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules       # to prevent overwriting node_modules

  microapp-backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
