name: Backend Lint

on:
  push:
    paths:
      - "backend/**"
    branches: ["**"]
  pull_request:
    paths:
      - "backend/**"
    branches: ["**"]

permissions:
  id-token: write
  contents: read
  actions: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      has_backend_changes: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            backend:
              - 'backend/**'

  black:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.has_backend_changes == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
        working-directory: ./backend
      - run: black --check .
        working-directory: ./backend

  ruff:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.has_backend_changes == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
        working-directory: ./backend
      - run: ruff format .
        working-directory: ./backend
      - run: ruff check .
        working-directory: ./backend
